parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
Traceback (most recent call last):
  File "parGALE.py", line 190, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "parGALE.py", line 174, in GALE
    collect.extend(p.map(partial_gale1, per))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: need more than 1 value to unpack
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
Terminated
Process PoolWorker-8:
Process PoolWorker-7:
Process PoolWorker-5:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-2:
Traceback (most recent call last):
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-3:
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-4:
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-1:
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-6:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.run()
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    result = (True, func(*args, **kwds))
    return map(*args)
  File "parDE.py", line 122, in de1
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
  File "parDE.py", line 99, in de0
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
    oldVal=model.solve(now)
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    sleep(0.5)
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
    sleep(0.5)
    sleep(0.5)
KeyboardInterrupt
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
Terminated
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
