parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:51: RuntimeWarning: overflow encountered in exp
  return np.exp(loss1(i,x,y) / n)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
Terminated
Process PoolWorker-3:
Process PoolWorker-2:
Process PoolWorker-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-1:
Traceback (most recent call last):
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.run()
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.run()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    result = (True, func(*args, **kwds))
    return map(*args)
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
  File "parDE.py", line 122, in de1
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    result = (True, func(*args, **kwds))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "parDE.py", line 122, in de1
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
  File "parDE.py", line 99, in de0
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    return de0(model,new=[],pop=int(pop/n_proc),iter=iter/n_proc)
  File "parDE.py", line 99, in de0
    oldVal=model.solve(now)
  File "/home/rkrish11/git/Experimental-Algorithms/multiProc/src/dtlz2.py", line 43, in solve
    sleep(0.5)
    sleep(0.5)
KeyboardInterrupt
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
    sleep(0.5)
KeyboardInterrupt
Terminated
User defined signal 2
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
parGALE.py:86: RuntimeWarning: invalid value encountered in double_scalars
  return (a**2-b**2+c**2)/(2*c)
